
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package comp;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 6;
  public static final int CIERRAPARENTESIS = 3;
  public static final int PUNTOYCOMA = 4;
  public static final int error = 1;
  public static final int ABREPARENTESIS = 2;
  public static final int ENTER = 5;
  public static final int EOF = 0;
  public static final int INT = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ABREPARENTESIS",
  "CIERRAPARENTESIS",
  "PUNTOYCOMA",
  "ENTER",
  "COMA",
  "INT"
  };
}

